use_frameworks!

platform :ios, '8.0'

target 'ZZScreenBrightness_Example' do
  pod 'ZZScreenBrightness', :path => '../'

  target 'ZZScreenBrightness_Tests' do
    inherit! :search_paths

    
  end
end
